
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydepo
  labels:
    app: game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: cont2
          image: yaseenbasha/httpd
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: game
  ports:
    - port: 80
      targetPort: 80
